baseURL: "https://ejeff.org/"
title: "Jeff Fredrickson"
languageCode: "en-US"
enableGitInfo: true
capitalizeListTitles: false

params:
  dateFormat: "January 2, 2006"

taxonomies:
  tag: tags

cascade:
  - _target:
      kind: section
      path: /photos/*
    layout: list
  - _target:
      kind: section
      path: /photos/*/**
    layout: album
  - _target:
      kind: page
      path: /photos/*/**
    layout: single

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "node_modules/@fortawesome/fontawesome-free/css"
      target: "static/vendor/fontawesome-free/css"
    - source: "node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/vendor/fontawesome-free/webfonts"
    - source: "node_modules/@fontsource"
      target: "static/vendor/fontsource"
    - source: "node_modules/lightgallery/css"
      target: "static/vendor/lightgallery/css"
    - source: "node_modules/lightgallery/fonts"
      target: "static/vendor/lightgallery/fonts"
    - source: "node_modules/lightgallery/images"
      target: "static/vendor/lightgallery/images"
