baseURL: "https://ejeff.org/"
title: "Jeff Fredrickson"
languageCode: "en-US"
enableGitInfo: true

params:
  dateFormat: "January 2, 2006"

taxonomies:
  tag: tags

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "node_modules/@fortawesome/fontawesome-free/css"
      target: "static/vendor/fontawesome-free/css"
    - source: "node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/vendor/fontawesome-free/webfonts"
    - source: "node_modules/lightgallery/css"
      target: "static/vendor/lightgallery/css"
    - source: "node_modules/lightgallery/fonts"
      target: "static/vendor/lightgallery/fonts"
    - source: "node_modules/lightgallery/images"
      target: "static/vendor/lightgallery/images"
